#pragma once
#include "APICommon.h"
#include <cuda.h>
#include <curand.h>
extern curandGenerator_t cuRandGen_;
extern size_t MPC, GS, CPM;
void LeakyReluForward(const __half* dataIn, __half* dataOut, int size, float negativeSlope, cudaStream_t stream = nullptr);
void LeakyReluBackward(__half* grad, const __half* dataIn, int size, float negativeSlope, cudaStream_t stream = nullptr);
void SwishForward(const __half* dataIn, __half* outData, int size, cudaStream_t stream = nullptr);
void SwishBackward(__half* grad, const __half* dataIn, int size, cudaStream_t stream = nullptr);
void SigmoidForward(const __half* dataIn, __half* dataOut, int numCtrls, int numButs, int size, cudaStream_t cudaStream = nullptr);
void SigmoidBackward(__half* grad, const __half* dataIn, int numCtrls, int numButs, int size, cudaStream_t cudaStream = nullptr);
void GELUForward(const __half* dataIn, __half* dataOut, int size, cudaStream_t stream = nullptr);
void GELUBackward(__half* grad, const __half* dataIn, int size, cudaStream_t stream = nullptr);
void AsinhForward(const __half* dataIn, __half* dataOut, int size, float alpha, cudaStream_t stream = nullptr);
void AsinhBackward(__half* grad, const __half* activated, int size, float alpha, cudaStream_t stream = nullptr);
void LayerNormForward(__half* y, const __half* x, const float* g, const float* b, float* mean, float* var, int N, int C, int HW, bool spatialMode);
void LayerNormBackward(__half* dx, const __half* dy, const __half* x, const float* g, float* dG, float* dB, const float* mean, const float* var, void* workspace, size_t workspaceSize, int N, int C, int HW, bool spatialMode);
void FeatureMapMosaic(const __half* dInput, unsigned char* dOutput, int H, int W, int inC, int mosaicW, int tileW, int tileH, int gridW, float scale, cudaStream_t stream = nullptr);
void WmmaAttention(const __half* Q, const __half* K, const __half* V, __half* Out, __half* AttentionWeights, const float* attentionMask, const float* relPosBias, const int* relPosIndex, int relPosSize, int batchSize, int tokens, int headDim, int heads, int maskBatchSize, int maskHeads);
void WmmaAttentionBackward(const __half* Q, const __half* K, const __half* V, const __half* dOut, const __half* Att, __half* dQ, __half* dK, __half* dV, float* dAttWorkspace, size_t workspaceElements, int batchSize, int tokens, int headDim, int heads);
void AccumulateRelPosBiasGrad(const float* dAtt, const int* relPosIndex, float* gradBias, int batchSize, int tokens, int heads, int relPosSize, float scale);
void ExtractPatches(const __half* in, __half* out, int B, int C, int H, int W, int P);
void CombinePatchGrads(const __half* dy, __half* dx, int B, int C, int H, int W, int P);
void SumPositionalGrad(const __half* grad, __half* out, int B, int C, int P, bool first, float scale);
void TanhInPlace(__half* data, int size);
void TanhBackward(__half* grad, const __half* activations, int size);
void AttentionPoolForward(const __half* input, const __half* query, __half* output, float* attnWeights, float* tempBuffer, int batchSize, int tokens, int embedDim, int numQueries, float invSqrtDim);
void AttentionPoolBackward(const __half* grad, const __half* input, const __half* query, const float* attnWeights, float* tempBuffer, float* batchSums, __half* outGrad, __half* gradQuery, int batchSize, int tokens, int embedDim, int numQueries, float invSqrtDim);
void ScaleArrayHalf(__half* data, size_t count, float scale);
void AddBias(__half* output, const __half* bias, int channels, int batchSize);
void AddTensor(float alpha, __half* A, float beta, const __half* B, size_t size);
void AddTensorBroadcast(float alpha, const __half* B, float beta, __half* C, int batch, int elementsPerBatch);
void AccumulateBiasGrad(const __half* grad, __half* gradBias, int channels, int batchSize, float scale, bool reset);
void PackColumnsToHeads(const __half* inputQ, const __half* inputK, const __half* inputV, __half* outputQ, __half* outputK, __half* outputV, int batch, int tokens, int embedDim, int numHeads);
void PackColumnsToHeads(const __half* input, __half* output, int batch, int tokens, int embedDim, int numHeads);
void PackHeadsToColumns(const __half* inputQ, const __half* inputK, const __half* inputV, __half* outputQ, __half* outputK, __half* outputV, int batch, int tokens, int embedDim, int numHeads);
void PackHeadsToColumns(const __half* input, __half* output, int batch, int tokens, int embedDim, int numHeads);
void PatchMerge(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols);
void PatchUnmerge(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols);
void TokensToSpatial(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols);
void SpatialToTokens(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols);
void TokensToWindows(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols, int windowHeight, int windowWidth, int shiftHeight, int shiftWidth);
void WindowsToTokens(const __half* input, __half* output, int batch, int tokens, int embedDim, int patchRows, int patchCols, int windowHeight, int windowWidth, int shiftHeight, int shiftWidth);
void ScaleNearestNeighborForward(const __half* input, __half* output, int batch, int channels, int inHeight, int inWidth, int outHeight, int outWidth);
void ScaleNearestNeighborBackward(const __half* gradOut, __half* gradIn, int batch, int channels, int inHeight, int inWidth, int outHeight, int outWidth);
void DropPathBuildMask(float* mask, int batch, float keepProb);
void DropPathApply(__half* data, const float* mask, int batch, int elementsPerBatch);
void DropoutForward(__half* data, unsigned char* mask, int size, float keepProb, unsigned long long seed);
void DropoutBackward(__half* grad, const unsigned char* mask, int size, float keepProb);
int ConvertSmVer2Cores(int major, int minor);
void GetLaunchConfigGridStride(size_t n, size_t& blocks, size_t& tpb);
void WeightInit(__half* weights, int elementCount, int fanIn, int fanOut, WeightInitMethod method);